--테이블 현황
SELECT TABLE_NAME
FROM USER_TABLES;

--DML (INSERT, UPDATE, DELETE)

CREATE TABLE A_ENROL
AS
SELECT * 
FROM ENROL
WHERE STU_NO < 20150000;

DESC A_ENROL; --구조보기
SELECT * FROM A_ENROL;

----INSERT
INSERT INTO A_ENROL(SUB_NO,STU_NO,ENR_GRADE) --명시적 방법
VALUES(108,20151062,92);
SELECT * FROM A_ENROL;

INSERT INTO A_ENROL --임의적 방법
VALUES(111,20153075,NULL);
SELECT * FROM A_ENROL;

INSERT INTO A_ENROL(SUB_NO,STU_NO)
VALUES(110,20152088); --명시적 방법에서 빠진부분은 NULL값으로 임의적 방법은 빠진부분 있으면 안됨

--복수행 삽입
SELECT * FROM A_ENROL
WHERE STU_NO LIKE '2015%';

--EX)2015학번들을 A_ENROL테이블에 넣기
INSERT INTO A_ENROL
SELECT * FROM ENROL
WHERE STU_NO LIKE '2015%';
SELECT * FROM A_ENROL;


----UPDATE
UPDATE A_ENROL
SET ENR_GRADE = ENR_GRADE+5;
SELECT * FROM A_ENROL;

--EX)과목번호가 101인 학생만 5점 추가
UPDATE A_ENROL
SET ENR_GRADE = ENR_GRADE+5
WHERE SUB_NO = 101; --조건문에 의해서도 가능
SELECT * FROM A_ENROL;

--EX)과목이름이 '시스템분석설계'인 학생에 대해서만 점수 +10
SELECT * FROM SUBJECT;
SELECT * FROM A_ENROL;

UPDATE A_ENROL
SET ENR_GRADE = ENR_GRADE +10
WHERE SUB_NO = (SELECT SUB_NO 
FROM SUBJECT
WHERE SUB_NAME = '시스템분석설계');
SELECT * FROM A_ENROL;


----DELETE 

--EX)학번이 20131001인 학생 테이블 삭제
DELETE FROM A_ENROL 
WHERE STU_NO = 20131001;

--EX)과목이름이 '기계요소설계'인 과목을 수강하는 학생의 수강테이블 삭제
DELETE A_ENROL --FROM 생략 가능
WHERE SUB_NO = (SELECT SUB_NO
FROM SUBJECT
WHERE SUB_NAME = '기계요소설계');
SELECT * FROM A_ENROL;

--모든 테이블 삭제
DELETE FROM A_ENROL;
SELECT * FROM A_ENROL;

--다시 복원
ROLLBACK;

--TCL (COMMIT,ROLLBACK)
SELECT * FROM B_STUDENT;
DELETE FROM B_STUDENT;
ROLLBACK;
SELECT * FROM B_STUDENT;

CREATE TABLE C_STUDENT
(STU_NO NUMBER,
STT_AME CHAR(10)); --DDL에는 COMMIT이 자동으로, ROLLBACK이 안됨!
ROLLBACK;

SELECT * FROM B_STUDENT;
SELECT * FROM A_STUDENT;
DELETE FROM A_STUDENT;
SELECT * FROM A_STUDENT;
ROLLBACK;
SELECT * FROM A_STUDENT;

INSERT INTO A_STUDENT(STU_NO, STU_NAME)
VALUES(10,'홍');
SELECT * FROM A_STUDENT; --CMD에서는 안보임
COMMIT; --COMMIT을 하면 CMD에서 보임 (COMMIT을 해야 다른 로컬이나 서버에도 적용)
